spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manage?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    filters: wall,mergeStat
