server:
  port: 8080
logging:
  level:
    com.example.demo: DEBUG
spring:
  application:
    name: manage
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  redis:
    #数据库索引
    database: 0
    host: 121.196.48.181
    port: 6379
    password:
    timeout: 5000 #链接超时时间
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0

  loginCode:
    expiration:2

  mybatis:
    mapper-locations: classpath*:**/dao/*.xml
    configuration:
      database-id: mysql
jwt:
  config:
    timeout: 3600000 #token过期时间一小时
upload:
  path: upload/** #静态文件访问
  address: D://manage/upload/ # 开发环境上传文件地址
  # address: /usr/java/manage/upload/ #生产环境上传文件地址